# Generated by Django 4.2.1 on 2023-10-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
