# Generated by Django 5.0 on 2023-12-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
    ]
